= Code Formatting

== Clang Format
Code format is verified at commit and required for PRs.
This is done by `clang-format`.
The config file (`.clang-format`) is present at the root of the project.

=== IDE Clang Format
IDEs might also provide built in support for `clang-format`:

* CLion: Settings -> Editor -> Code Style -> ClangFormat
* VSCode: The https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools[C/C++ Extension] provides support for clang-format code formatting. This can be enabled through the properties:
** `editor.formatOnSave`
** `editor.formatOnType` - formatting upon typing the `;` character

=== Git Clang Format
`clang-format` also provides `git-clang-format`, which can be used to validate the format of the current working changes.

Executing `git-clang-format` before every commit can be tiresome.
Because of this, a git pre-commit hook can be used to invoke `git-clang-format`

Sample pre-commit hook below.

.`.git/hooks/pre-commit`
[source]
----
#!/bin/bash
#
# Hook script to verify what is about to be committed is appropriately formatted.
#
# Instructions:
#  * Copy this file to $(git rev-parse --git-dir)/hooks/pre-commit.
#  * Set BIN_DIR to the path to 'clang-format' binary and 'git-clang-format' script.
#  * Make sure that 'git-clang-format' is has its' execution flag set.
#
# If you want something more advanced, like automatically formatting files,
# you can look at existing scripts at your own risk, of course, such as
# https://github.com/barisione/clang-format-hooks.

set -euo pipefail

# Use clang-format.
BIN_DIR="path/to/clang-format/binary"
CLANG_FORMAT="${BIN_DIR}/clang-format"
GIT_CLANG_FORMAT="${BIN_DIR}/git-clang-format"

if git rev-parse --verify HEAD >/dev/null 2>&1
then
  AGAINST=HEAD
else
  # Initial commit: diff against an empty tree object
  AGAINST=$(git hash-object -t tree /dev/null)
fi

# Redirect output to stderr.
exec 1>&2

# Print formatting diff and exit with a non-zero value
# if any file needs to be reformatted.
if ! "${GIT_CLANG_FORMAT}" --extension c,cpp,h,hpp \
    --binary "${CLANG_FORMAT}" \
    --commit "${AGAINST}" --staged --diff
then
  echo "Some files need to be reformatted before being committed."
  exit 1
fi

----

