= Setting up your environemnt

This section contains the initial setup of the environment

== Dependencies

=== For Base Targets

- install https://git-scm.com/book/en/v2/Getting-Started-Installing-Git[git]

- install https://cmake.org/install/[cmake], minimum version 3.15

- install clang, latest stable version.

Submodules should also be fetched by either of the following:

- `git clone --recurse-submodules <repo>` at clone

- `git checkout --recurse-submodules <branch>` at branch switch

- `git submodule update --init --recursive` once on the desired branch

=== For Visualizer Targets

In addition to the Base Targets requirements, to enable visualizer targets, the following are required:

- https://www.qt.io/download-qt-installer-oss[Qt Open Source] binaries, either Qt5 or Qt6.


== Building the Binaries

=== Manually

==== Base Targets
Clone the project

[source,bash]
----
git clone --recurse-submodules https://github.com/LoghinVladDev/AGE.git
----

Build the targets using cmake

Setup cmake for base targets

[source,bash]
----
# If using another compiler, or clang is not in the env Path, provide your own values

cmake -S . -B build -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
----

Setup cmake for base and visualizer targets

[source,bash]
----
# If using another compiler, or clang is not in the env Path, provide your own values

# Path to Qt binaries can be provided by either QT5_PATH or QT6_PATH.
# Path must be to binaries, not to Qt installation
# The binaries are usually in the Qt install folder -> version -> architecture.
# Example, on x86_64 linux for Qt 6.3.0: /path/to/qt/6.3.0/gcc_64

cmake -S . -B build -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DQT6_PATH="/path/to/your/qt/binaries"
----

The base available build targets are:

- `unit_tests` - binary executing all standard unit tests
- `visualizer` - binary of the graph visualization and editing application
- `visualizer_mock` - mock binary of the graph visualization (separate unit test)
